name: Docker Image CI

on:
  workflow_dispatch
	

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag softether:latest

	  - name: Run container
	    run: docker run -dit --rm --name softether localhost/softether:latest bash
	  
  	- name: Copy File From Container
	    run: docker cp softether:/home/user/software /mnt
	  
  	- name: Upload firmware directory
    - uses: actions/upload-artifact@main
	     with:
	    	name: softether_software
	    	path: /mnt/software
